### ISSUE TITLE
Respect custom paths for icons in core.js AjaxRequest::toggleVisibility()

### ISSUE THREAD

**Issue by DanielSchwiperich** [contao-components/contao#1]
If a bundle defines a custom page type for example and uses the core-bundle Hook `getPageStatusIcon` a public accessible path is returned like `bundles/mybundle/custom_page_type-icon.gif`

The icon then is shown correct in the page tree. But if the "Hide/Unhide" (eye) Icon is clicked the image disappears because of a smal bug in AjaxRequest::toggleVisibility().
See here:
https://github.com/contao-components/contao/blob/master/js/core.js#L518
and here:
https://github.com/contao-components/contao/blob/master/js/core.js#L545
and maybe here also:
https://github.com/contao-components/contao/blob/master/js/core.js#L573

`img.src = AjaxRequest.themePath + (!published ? icon : icond);`
The problem here is that `AjaxRequest.themePath` is prepended which works fine for core icon where only the icon name is set and the path finding is handled by `Contao\Image::getHtml` but not for custom icons where the data attributes contain the full web url relative path. 

Core Icon with name only:
```html
<img src="system/themes/flexible/images/regular.gif" data-icon="regular.gif" data-icon-disabled="regular_1.gif" height="18" width="18">
```
Custom icons with complete path (relative to web folder)
```html
<img src="/bundles/mybundle/custom_page_type-icon.png" data-icon="/bundles/mybundle/custom_page_type-icon.png" data-icon-disabled="/bundles/mybundle/custom_page_type-icon_1.png" height="14" width="18">
```
(Doesn't matter it with or without / at path start)

This is then converted to `system/themes/flexible/images/bundles/mybundle/custom_page_type-icon_1.png`

An easy fix could be to only prepend `AjaxRequest.themePath` if the icon / icond do not contain slashes / a path

**Comment by leofeyer** [comment]
This issue occurs in Contao 3 as well, doesn't it?

**Comment by DanielSchwiperich** [comment]
I did not validate it, since the my test case / module is only contao 4, and I didn't find a contao 3 module where we use the hook, but looking at https://github.com/contao/core/blob/master/assets/contao/js/core-uncompressed.js the bug must also exists in contao 3.

If you like / need I could setup a test module on the weekend for contao 3 to test it.
