### ISSUE TITLE
Contao 5 - Update layout.css

### ISSUE THREAD

**Issue by contaoacademy** [contao-components/contao#15]
### Affected version(s)

5.0.1

### Description

The new CSS classes are not included in `layout.css`.

For example:

- `float_left` = `media--left`
- `float_right` = `media--right`
- `ce_gallery` = `content-gallery`

Also see: https://github.com/contao/contao/issues/5219

**Comment by leofeyer** [comment]
Fixed in 2d3b569ca3b38e935597b83de3a4f75257796aa6.
