### ISSUE TITLE
Clearing floats in layout.css not working in content elements

### ISSUE THREAD

**Issue by mdollde** [contao-components/contao#17]
Clearing floats in the layout.css is done with
```
/**
 * Clear floats
 */
.block {
	overflow:hidden;
}
.clear,#clear {
	height:0.1px;
	font-size:0.1px;
	line-height:0.1px;
	clear:both;
}
```

There is no block class for content elements in the twig templates, hence the clearing does not work anymore. For content element text you could add

```
/**
 * Clear floats
 */
.block, .media {
	overflow:hidden;
}
```
or
```
/**
 * Clear floats
 */
.media {
	display: flow-root;
}
```

Greetings
Mathias

**Comment by leofeyer** [comment]
We‘ll discuss this in the next Contao call.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add `.media { display: flow-root; }` in the `layout.css` style sheet.
