### ISSUE TITLE
Missing declaration in layout.css for image alignment below

### ISSUE THREAD

**Issue by mdollde** [contao-components/contao#18]
Image alignment below has no CSS declaration in layout.css.

In Contao 4 it was done within the template ce_text by changing the order of the html elements. With the new twig templates the order in the source code stays the same, so "Image alignment below" does not work, despite activating the Layout Builder in the page layout.

A possible solution could be an additional declaration to layout.css.

```
.media--below {
    display: grid;
 }

/* Move image below text */
.media--below > figure {
    order: 5;
}
```

Greetings
Mathias

**Comment by leofeyer** [comment]
I‘m not sure if this isn‘t rather a bug in the Twig template. 🤔

**Comment by leofeyer** [comment]
See #7113
