### ISSUE TITLE
File tree remove button has wrong type

### ISSUE THREAD

**Issue by ausi** [contao-components/contao#5]
The delete buttons of gallery file trees have the type `submit` which leads to the following error:

1. Create a gallery content element
2. Select an image
3. Klick into the headline field
4. Press <kbd>Enter</kbd>
5. Instead of submitting the form, the image gets removed because <kbd>Enter</kbd> triggers the first submit button inside the current form

Coud be fixed by changing [core.js:1424](https://github.com/contao-components/contao/blob/7b8b7cd56164c46af2f34bf7b22999f69e163031/js/core.js#L1424) and [core.js:1435](https://github.com/contao-components/contao/blob/7b8b7cd56164c46af2f34bf7b22999f69e163031/js/core.js#L1435) to:

```js
new Element('button', {
	type: 'button',
	html: '&times;',
	...
```

**Comment by leofeyer** [comment]
Fixed in 43d8125d21fdfc46b3ee4a7a887fac29968fa491.
